services:
  site:
    image: consol/omd-consol-de
    build:
      context: .
    command: server
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:1313/ || exit 1
      interval: 5s
      retries: 5
      start_period: 120s
      timeout: 10s
