---
apiVersion: v1
kind: Service
metadata:
  name: omd-consol-de-service
  namespace: ocd
spec:
  selector:
    app: omd-consol-de
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer

