---
apiVersion: v1
kind: Service
metadata:
  name: omd-consol-de-service
  namespace: ocd
spec:
  selector:
    app: omd-consol-de
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30008
  - name: goaccess
    port: 8000
    targetPort: 8000
    nodePort: 30009
  #type: LoadBalancer
  type: NodePort

